---
- name: Deploy Kubernetes Cluster Nodes
  hosts: kvm_host
  become: true
  vars:
    ssh_public_key: ~/.ssh/id_ed25519.pub
    k8s_nodes:
      - name: k8s-control
        memory: 4096
        vcpus: 2
        disk: 50G
      - name: k8s-worker1
        memory: 4096
        vcpus: 2
        disk: 50G
      - name: k8s-worker2
        memory: 4096
        vcpus: 2
        disk: 50G
    network: k8s-net
    bridge: virbr2

  tasks:
    - name: Download Ubuntu 20.04 cloud image if not present
      ansible.builtin.get_url:
        url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
        dest: /tmp/ubuntu-20.04-cloudimg.img
        mode: '0644'

    - name: Create cloud-init configs for all nodes
      ansible.builtin.include_tasks: tasks/create-k8s-node.yml
      loop: "{{ k8s_nodes }}"
      loop_control:
        loop_var: node

- name: Display Cluster Status
  hosts: kvm_host
  become: false
  tasks:
    - name: Show all K8s nodes
      ansible.builtin.command:
        cmd: virsh list --all
      register: vm_list
      changed_when: false

    - name: Display VMs
      ansible.builtin.debug:
        msg: "{{ vm_list.stdout_lines }}"

    - name: Get DHCP leases
      ansible.builtin.shell:
        cmd: set -o pipefail && virsh console vyos-router --force <<< 'show dhcp server leases' | grep k8s
        executable: /bin/bash
      register: k8s_leases
      changed_when: false
      failed_when: false

    - name: Display K8s IPs
      ansible.builtin.debug:
        msg: "{{ k8s_leases.stdout_lines }}"
