---
- name: Create AWX namespace
  ansible.builtin.shell: |
    set -o pipefail
    kubectl create namespace {{ awx_namespace }} --dry-run=client -o yaml | kubectl apply -f -
  args:
    executable: /bin/bash
  changed_when: false

- name: Install AWX Operator
  ansible.builtin.command:
    cmd: kubectl apply -f https://github.com/ansible/awx-operator/releases/{{ awx_version }}/download/awx-operator.yaml
  changed_when: false

- name: Deploy AWX instance manifest
  ansible.builtin.copy:
    dest: /tmp/awx.yaml
    mode: '0644'
    content: |
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: awx
        namespace: {{ awx_namespace }}
      spec:
        service_type: NodePort
        nodeport_port: 30080

- name: Apply AWX manifest
  ansible.builtin.command:
    cmd: kubectl apply -f /tmp/awx.yaml
  changed_when: false

