---
- name: Ensure base packages are present
  become: true
  ansible.builtin.package:
    name:
      - curl
      - python3
      - iptables
      - ca-certificates
    state: present

- name: Disable swap (K3s requirement)
  become: true
  ansible.builtin.command:
    cmd: swapoff -a
  when: ansible_swaptotal_mb | int > 0
  changed_when: false

- name: Comment out swap entries in /etc/fstab
  become: true
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*swap)'
    replace: '# \1'
